### ISSUE TITLE
User-can-search-their-entries

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/code-journal#11]
## 💰 Motivation

If the entries become too long, user should have a way to find their entry manually.

## 📐 Plan

Provide a search box that causes the entries list to only show matches.

## ✅ Task List

- [x] Add a search box to the top of the entries page
- [x] When user submits their entry, write a script that will search for the entry by title in data file
- [x] Make sure if title doesn't match, return "no match"
- [x] Add references to each li element through appending on JS
- [x] Ensure when search matches, page will scroll smoothly to referenced area
